# Git and Github


With our guest lecturer, Seb James


```{block, type="info"}
*Note this is a placeholder page. This material hasn't been taught yet. I am adding notes online as I can, so these pages in particular may evolve quickly*
```


## Before the class

Create an account on [github.com](https://github.com/), if you don't already have one.

Install git on your machine. 

  * On Windows: https://git-scm.com/download/win
  * On Mac: https://git-scm.com/download/mac
  
Until you do that you DON'T have the git features enabled in RStudio.


## Accessing git 

If you have RStudio you can access git using point and click (top right), or via the terinmal (the tab next to Console on the bottom right). 

Outside of RStudio:

 * Students using windows can install: https://gitforwindows.org/ Once installed they should be able to open a git bash window and type ``git --version``
 * Students on a Mac will have git if they install 'Xcode' and 'Command line tools for Xcode'.They can test by opening a terminal and typing ``git --version``


## Resources for the class

This week's class is taught by Seb James. Links to his materials are below

  * Intro to git talk: https://github.com/ABRG-Models/GitTutorial
    * PDF of slides: https://github.com/ABRG-Models/GitTutorial/blob/master/talk.pdf
  * Software carpentry: http://sebjameswml.github.io/git-novice/

Examples of two published projects supported by Github repos

  * https://github.com/ABRG-Models/AttractorScaffolding
  * https://github.com/ABRG-Models/linetask2014
  * https://github.com/ABRG-Models/BarrelEmerge/tree/eLife_submission1_full

## Exercise - publishing your project with github pages

Git and github are fundmental tools which will be relevant for collaborating on reliable computational projects, but it is not essential you master the full range of capabilities they offer for this module.

The only essential from this class is that you can use github to publish an analysis. Follow the steps on [Publishing](publishing.html) to check you can do this. 

Now is a good time to start preparing your [final project](final-project.html): chosing some data, creating a project folder and a RMarkdown document to introduce the data and any graphs you have drawn (or plan to draw).


## Bonus Reading

Official documentation: [github pages](https://help.github.com/en/github/working-with-github-pages)

[Understanding Git Conceptually](https://www.sbf5.com/~cduan/technical/git/)

Vuorre, M., & Curley, J. P. (2018). [Curating research assets: A tutorial on the git version control system](https://journals.sagepub.com/doi/full/10.1177/2515245918754826). Advances in Methods and Practices in Psychological Science, 1(2), 219-236.