# Overview, assessment & module organisation

## Class material:
  
Materials from the class are in the PSY6422 [Google Drive](https://drive.google.com/drive/folders/1c0GOBwwbaxiVcyZKr7QKcZOG6i-_d7by?usp=sharing) (UoS login required to access). Slides : [slides format](https://docs.google.com/presentation/d/15RlRzRGL3fa1SckE8YUWhJxiuWf5GH5pssIcG2zStKM/edit?usp=sharing).

## Exercise 1 (assessed!)

The exercise for this class is an initial self-assessment, which comprises part of your final grade. The deadline is in two weeks - see the timetable.

Submit using the form link provided by Tom [check your email] a document of no more than one A4 page (i.e. less than 500 words):

Aim 1: tell me what you know already  

 * review course webpages, write ~50 words on your experience with computers and coding

Aim 2: start thinking about data to visualise  

 * describe a dataset you have access to and what you’ll do with it OR  
 * describe the kind of topic you'd like to identify relevant data to do a project on

Aim 3: set some targets for what you’d like to learn next  

 * describe 1 or 2 ambitions; techniques, technologies or tools you'd like to acquire

### Marking criteria: 

See the assessment document

The purpose of this assessment is to ensure you are engaging with the course and to start a conversation between us about the final assessment. I want to give you 100%, all you have to do to achieve this is follow the instructions above.


### Submission

You submit using them form link supplied by me, as an attachment with a filename containing your surname and registration number, of the form:

|     surname_000000000.pdf

(file format does not need to be pdf)




## Checklist:

*To complete this class you should do the following :*

* Review these webpages
  * identify topics covered
  * locate timetable
  * note assessment deadlines

* Complete initial self-assessment by deadline

* Check you have received email from Tom
  * Used the link to join the slack group
  

## Resources

### Further reading on the motivation for a data management component of this course

* Russ Poldrack's [Advice for learning to code from scratch ](http://www.russpoldrack.org/2016/05/advice-for-learning-to-code-from-scratch.html)
* Neuroskeptic on a [true story of data analysis error](http://neuroskeptic.blogspot.com/2011/04/tufnel-effect.html) (and how you can avoid it) "if you're doing something which involves 100 steps, it only takes 1 mistake to render the other 99 irrelevant."
* [Data Sharing and Management Snafu in 3 Short Acts](https://www.youtube.com/watch?v=66oNv_DJuPc)


