# Advanced Topics

```{block, type="info"}
*Note this is a placeholder page. This material hasn't been taught yet. I am adding notes online as I can, so these pages in particular may evolve quickly*
```

Rather than teach substantive content, in this class I will showcase important advanced topics which you may wish to explore after the course. The idea is that it will be faster for you to set out on your own with a quick overview of the data science landscape. This way at least you will have heard of potential solutions when you encounter future problems.


## Interactive graphs

Using Shiny Apps

 * RStudio: [Shiny User Showcase](https://shiny.rstudio.com/gallery/)
 * Example: [Movie-explorer](https://shiny.rstudio.com/gallery/movie-explorer.html)
 * Example: [Enhanced sensitivity to group differences with decision modelling](https://sheffield-university.shinyapps.io/decision_power/)

Javascript!

 * [Interpreting Cohen's d Effect Size](https://rpsychologist.com/d3/cohend/) by Kristoffer Magnusson
 * Example: Grid histograms of [Constituencies by median age in 2017](https://olihawkins.com/visualisation/14) from Oli Hawkins

## Reproducibility

Dependencies
 * Package management 
    * renv: https://github.com/rstudio/renv
    * e.g. https://luisdva.github.io/rstats/annotater/
 * Containers
    * e.g. [docker](https://www.docker.com/)

## Preview of other advanced topics

Remote access via the command line and ssh

  * We will use these files [prime_search.R](static/primesearch.R) and [pyprime_search.py](static/pyprime_search.py)

[Python](https://tomstafford.github.io/psy6422/notes.html#python)

SQL



