# R & R Studio

## Resources

* Statistical computing using R, the open source programming language, and the [R Studio interface](https://rstudio.com/).
* Guide: [How to install R and RStudio?](https://www.r-bloggers.com/2019/12/how-to-install-r-and-rstudio-2/)
* [https://swirlstats.com/](https://swirlstats.com/students.html)
* Nick HK Troubleshooting [Common Problems](https://nickch-k.github.io/DataCommSlides/Lecture_04_Common_R_Problems.html)
* r-bloggers.com [Top 10 errors in R and how to fix them](https://www.r-bloggers.com/2023/02/top-10-errors-in-r-and-how-to-fix-them/)
* [rtutor.ai/](http://rtutor.ai/) - natural language interface to R

## Exercises


* install R on your computer
  * if you can't, use the cloud: [posit.cloud](https://login.posit.cloud) [log in with Google and your \@sheffield.ac.uk account]

* open this [script](static/class2.R) 
  * review line by line [as a pair exercise]

* know how to install and load a library of functions ("a package")
  * install the swirl package

## Checklist

*To complete this class you should be able to do the following :*

* have R and RStudio installed and working correctly

* create a new project

* identify the console
  * here you can enter a command directly (e.g. "2 + 2")

* identify the file window

* save a script as a .R file

* run a single line of the script by pressing CTRL + ENTER

* run the whole script

* identify the environment window

* identify the files/plots/etc window

