# Data Wrangling 

```{block, type="info"}
*Note this is a placeholder page. This material hasn't been taught yet. I am adding notes online as I can, so these pages in particular may evolve quickly*
```

This class is about loading, cleaning, inspecting, merging and summarising data using the [Tidyverse](https://www.tidyverse.org/) library for data science. The majority of most data science projects is getting the data into the best form for plotting or analysis, what is called data cleaning, data munging or data wrangling.


## Class material

There are no slides for this class, it is taught entirely in workshop format.

## Exercises

Find the folder `/modelproject_asrs` in the google drive  
* review the project organisation and files
* open the file `datawrangle_exercises.R`
* complete the tasks described
  
## Checklist

You should leave being familiar with these concepts, and known where to look up how to implement them. Indented bullets are more advanced topics (not always covered in the exercise)
  
* Load data from CSV
  * load data from an excel file
  * load data from a TSV file (tab separated values)
  
* Recognise common tidyverse functions (below)
* Use the pipe operator `%>%`
* Mutate: new columns by combining old ones
  * Use string functions on column values (e.g. separate on characters, take substrings)
* Select: select columns
* Filter: select rows by values
* group_by and summarise
  * Understand this is a specific example of a general method of split-apply-combine
* rename: to change column names
* convert variable types, e.g. using as.numeric
* join: to merge data frames, requires a common key between data frames
  * understand inner joins, left and right joins

Almost any data wrangling task you can imagine can be done, you just need to find the right function or functions. So the final item for this classes checklist is

* practice searching for solutions to your data wrangling problems

## Resources
  
* Data Skills for Reproducible Science: [Data Wrangling](https://psyteachr.github.io/msc-data-skills/dplyr.html)
* Claudia A Engel: [Data Wrangling with R](https://cengel.github.io/R-data-wrangling/dplyr.html)
* R for Data Science: Part II [Wrangle](https://r4ds.had.co.nz/wrangle-intro.html), especially [Chapter 12 Tidy Data](https://r4ds.had.co.nz/tidy-data.html) and [Chapter 13 Relational Data](https://r4ds.had.co.nz/relational-data.html)
* datacarpentry.org [Data Wrangling with dplyr and tidyr](https://datacarpentry.org/r-socialsci/03-dplyr-tidyr/index.html)