# Appendices {-} 


## Credit

These pages based on [a template](https://psyteachr.github.io/book-template/) published by the awesome [psyTeachR team](https://psyteachr.github.io/about/). Extra thanks to Lisa DeBruine for help.

Find the repo here: [https://github.com/tomstafford/psy6422/](https://github.com/tomstafford/psy6422/)


## Help plz

Why doesn't the TOC in the leftbar collapse when clicked (or toggle between open and collapsed [like it should](https://psyteachr.github.io/book-template/))?

Here's is the [relevant page of the manual](https://bookdown.org/yihui/bookdown/html.html)

You can see that I have 

```{r}
collapse: section
```

in my ``_output.yml`` file [here](https://github.com/tomstafford/psy6422/blob/master/_output.yml). Why doesn't it work

How do I get a horizontal line in the TOC/sidebar?


## Python

This course teaches general principles of coding and computation, and specific skills for data management and visualisation in R. Lots of people in the data science world, particularly in areas which align with computer science / machine learning, use Python.

I decided to teach this course in R because the community around a language is as important as the language. You can do anything in any language, and most things as easily in Python as in R, but Psychologists, biologists and scholars from across the social sciences tend to use R, so I'm teaching this course in R.

If you want to learn Python, I recommend:

* Resource list: [Python for Non-Programmers](https://wiki.python.org/moin/BeginnersGuide/NonProgrammers)
* Pages [RealPython: Learn Python Programming, By Example](https://realpython.com/start-here/)
* Book: [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) by Jake VanderPlas
* Book: [Python for Data Analysis](https://wesmckinney.com/pages/book.html) by Wes McKinney
* Pages: [chrisalbon.com](https://chrisalbon.com/)
* Pages: [TowardsDataScience](https://towardsdatascience.com), for example this one [A Quick Introduction to the “Pandas” Python Library](https://towardsdatascience.com/a-quick-introduction-to-the-pandas-python-library-f1b678f34673)
* Book: [Python for Experimental Psychologists](http://www.pygaze.org/pep/) by Edwin Dalmaijer
* Pages: [w3Schools](https://www.w3schools.com/python/default.asp)

## General righteousness

You should use a password manager. Really. [LastPass](https://www.lastpass.com) is recommended

You should know how to use a VPN

* Advice for Sheffield students here: [Working remotely - information for students](https://www.sheffield.ac.uk/it-services/remote/students)
* You can test by visiting [this page](https://journals.sagepub.com/doi/full/10.1177/0956797613511466). If you are in the University network (either on campus or via a VPN) it will offer you the chance to download the article PDF. Otherwise it will try and charge you $35 for the privilege.


## Testimonials

[Peter Carr](https://www.sheffield.ac.uk/psychology/prospectivepg/masters/stories/peter-carr-1.817457)