# Advanced Topics {-}

```{block, type="info"}
*Note this is a placeholder page. This material hasn't been taught yet. I am adding notes online as I can, so these pages in particular may evolve quickly*
```

The first ten topics of this course represent the core that I want every student to take away from the course. With these topics you should be equiped to focus on your personal data project for which makes up the majority of the grade on the course.

The remaining time in the timetable is available for supervision on this data project, and to cover more advanced topics. For these topics, rather than provide a lecture, we will work in small groups to follow exercises and tutorials which exist outside of the course. The motivation for this is two-fold. First, because all your future work will be teamwork, I want students to graduate from this course with experience working together on technical projects. Whether you are more or less confident in the technical requirements, you will learn a lot from trying to share what you know or think you know with a group. Second, a key skill for ongoing development in data science is to teach yourself. There world is rich in useful advice, tutorials and examples. Only by discovering how you can use these will you maximise your potential after you have finished this module.

## 2021

In 2021 we votes on the advanced topics to cover in class:
* [interactive plots with shiny](120-shiny.html)
* [animated plots with gganimate](130-gganimate.html)
* [SQL](1140-sql.html)
* python


## Reproducibility

Dependencies

 * Package management 
    * https://groundhogr.com/
    * renv: https://github.com/rstudio/renv
    * e.g. https://luisdva.github.io/rstats/annotater/
 * Reproducible workflows
    * [Targets](https://books.ropensci.org/targets/) (was Drake)
 * Containers
    * e.g. [docker](https://www.docker.com/)



