# Notes

## Credit

These pages based on [a template](https://psyteachr.github.io/book-template/) published by the awesome [psyTeachR team](https://psyteachr.github.io/about/). Extra thanks to Lisa DeBruine for help.

## Colophon

Find the repo here: [https://github.com/tomstafford/psy6422/](https://github.com/tomstafford/psy6422/)

Everything worked better when I:

* set GitHub pages to run off of Master/docs
* listened to Lisa and used bookdown at the CL, not knit in Rstudio, to render the pages: ``R -e 'bookdown::render_book("index.Rmd")'``
* installed [R 3.6](https://cran.r-project.org/bin/linux/ubuntu/README.html)
* installed tidyverse, bookdown, devtools and finally [Webex](https://github.com/PsyTeachR/webex).

## Python

This course teaches general principles of coding and computation, and specific skills for data management and visualisation in R. Lots of people in the data science world, particularly in areas which align with computer science / machine learning, use Python.

I decided to teach this course in R because the community around a language is as important as the language. You can do anything in any language, and most things as easily in Python as in R, but Psychologists, biologists and scholars from across the social sciences tend to use R, so I'm teaching this course in R.

If you want to learn Python, I recommend:

* Resource list: [Python for Non-Programmers](https://wiki.python.org/moin/BeginnersGuide/NonProgrammers)
* Pages [RealPython: Learn Python Programming, By Example](https://realpython.com/start-here/)
* Book: [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/) by Jake VanderPlas
* Book: [Python for Data Analysis](https://wesmckinney.com/pages/book.html) by Wes McKinney
* Pages: [chrisalbon.com](https://chrisalbon.com/)
* Pages: [TowardsDataScience](https://towardsdatascience.com), for example this one [A Quick Introduction to the “Pandas” Python Library](https://towardsdatascience.com/a-quick-introduction-to-the-pandas-python-library-f1b678f34673)
* Book: [Python for Experimental Psychologists](http://www.pygaze.org/pep/) by Edwin Dalmaijer
* Pages: [w3Schools](https://www.w3schools.com/python/default.asp)

## General righteousness

You should use a password manager. Really. [LastPass](https://www.lastpass.com) is recommended

You should know how to use a VPN

* Advice for Sheffield students here: [Working remotely - information for students](https://www.sheffield.ac.uk/it-services/remote/students)
* You can test by visiting [this page](https://journals.sagepub.com/doi/full/10.1177/0956797613511466). If you are in the University network (either on campus or via a VPN) it will offer you the chance to download the article PDF. Otherwise it will try and charge you $35 for the privilege.

## Careers

Inside or outside of research, data management and visualisation skills will be good for you career. Unlikely many high-technical skills, coding is highly accessible. Even in the world of software development, over half of programmers are [self-taught](https://www.infoworld.com/article/2908474/stack-overflow-survey-finds-nearly-half-have-no-degree-in-computer-science.html). But coding is relevant to more than just pure software jobs, [one report](https://www.burning-glass.com/research-project/coding-skills/) found that 20% of graduate-level jobs value coding as a skill, and this 20% paid 30% more than other graduate jobs.

More information:

* [Job profile: Data Scientist](https://www.prospects.ac.uk/job-profiles/data-scientist)
* [Data Scientist: Job Description](https://targetjobs.co.uk/careers-advice/job-descriptions/454123-data-scientist-job-description)
* University of Sheffield: [Career Connect](https://www.sheffield.ac.uk/careers/careerconnect)

## Testimonials

[Peter Carr](https://www.sheffield.ac.uk/psychology/prospectivepg/masters/stories/peter-carr-1.817457)

This is the first year the [MSc in Psychological Research Methods with Data Science](https://www.sheffield.ac.uk/psychology/prospectivepg/masters/data-science) has run, so more soon!