# Class of 2022

This was the third year for the [MSc in Psychological Research Methods with Data Science](https://www.sheffield.ac.uk/postgraduate/taught/courses/2022/psychological-research-methods-data-science-msc). The classes were back in person and we cracked on with the core motivation of PSY6422 - to set students up for their independent data science project, carried out over the summer, but also to ensure that they left the MSc with a complete data project they could show off as part of a portfolio.

There were too many students on the module this year to show all projects, so here are a few highlights:


## Advice for future students

<style>
  .alpha {
  text-align: right;
  color: darkblue;
  font-style: italic;
  padding-bottom: 15px;
  }
  .beta {
  text-align: left;
  color: green;
  font-style: italic;
  padding-bottom: 15px;
  }
  .gamma {
  text-align: right;
  color: brown;
  font-style: italic;
  padding-bottom: 15px;
  }
  .delta {
  text-align: right;
  color: red;
  font-style: italic;
  padding-bottom: 15px;
  }
</style>

As part of the module assessment I asked those who took the module what advice they would give to future students

<div class="gamma">I would definitely say choose a project topic that you are interested in. I have (quite tragically) loved every minute of developing my project since I am quite interested in the topic and found myself very invested in the outcome of the project.</div>

<div class="delta">Try not to get frustrated! I didn’t have any coding experience before starting this course, and you will be surprised at how far you can push yourself. If you told me I would be making an interactive plot at the start of this module I would’ve laughed.</div>

## Feedback

Here is some selected feedback from the class of 2022.

<div class="alpha">I went from not knowing how to code to creating my own data-wrangling script in the span of a few months, and I owe it to the teaching style employed during our sessions</div>

<div class="beta">I really enjoyed the freedom to self direct on this course. Spending hours trying to learn how to properly implement a function correctly became a lot more satisfying when I was working on a project of my own design.</div>

<div class="alpha">For the first time in my life, I really liked the ‘homework’ exercises. The mini projects such as the anscombe one really helped me work with R because there was a goal and something tangible to work with. I find it quite challenging to ‘think’ about how to code something, but having hands on experience with data really helps contextualize it for me so I was able to translate those skills to my own project!</div>

<div class="beta">I have enjoyed this course and feel it will be beneficial for my career in the future. The lab classes helped my learning but it was also crucial that I had access to video run-throughs of some sections like publishing as these aided me when I was struggling. I was very pleased with how clear the expectations were throughout the course; the distinct parts of the coursework were broken down clearly and explained giving me a good understanding of how I needed to approach the task.</div>

<div class="alpha">This course gave me a great understanding of the impact visualizations can have within your research.</div>

<div class="beta">Tom and Luke’s help was invaluable. Having two people within the class that could guide us made all the difference when facing certain problems.
</div>

<div class="alpha">I really enjoyed the final project. During classes I struggled a lot with the content but the final project I was able to go over everything we had learnt in my own time and understand it fully. This gave me a massive sense of accomplishment
</div>

<div class="beta">I strongly believe that showing live demonstrations of the coding was a very beneficial way of learning. This is because it allowed us to go back and watch the recording if we were stuck; listening to the explanations of the code, and why some things are done in certain ways, allowed me to further my understanding in this field a lot faster as I did not find myself stuck on the basic things. Furthermore, I also found it beneficial that there was some room for self-teaching, in terms of the more advanced topics. This is because it allowed us to set a threshold as to how much coding we could take on and understand, without being overwhelming. It allowed me to push myself only if I thought I could handle it, and then produce a visualisation that I was proud to show friends and family. This is extremely advantageous as it also demonstrates my ability to take on new challenges.</div>

<div class="alpha">Specifically, I appreciated the opportunity to ask Tom and Luke questions in-person when I was confused, as they helped me understand the philosophy behind how one should approach coding issues; they didn’t just tell me the answer – which would have crippled me in the long term – they gave me hints on how I could solve it myself.</div>

