--- 
title: "PSY6422 Data Management and Visualisation @ The University of Sheffield"
author: "Tom Stafford"
date: '`r Sys.Date()`'
bibliography:
- book.bib
- packages.bib
description: This is a template. Use it to start a new course book.
documentclass: book
link-citations: yes
site: bookdown::bookdown_site
biblio-style: apalike
---

```{r cite-packages, include = FALSE}
# automatically create a bib database for R packages
# add any packages you want to cite here
knitr::write_bib(c(
  .packages(), 'bookdown', 'tidyverse', 'kableExtra'
), 'packages.bib')

```


# Module Overview 

PSY6422 Data Management and Visualisation is part of the MSc in Psychological Research Methods with Data Science taught at The University of Sheffield by [Tom Stafford](http://tomstafford.staff.shef.ac.uk/)

*Note this is a placeholder page. In 2020 most of this material was delivered offline. I am adding notes online as I can, so these pages in particular may evolve quickly*
  
## Motivation

You are aiming to produce reproducible workflows - scripts that automate all steps between raw data and the final data in your papers.

Point and click solutions (spreedsheets, SPSS) are inadequate.

As well as being *reproducible* (by you or other researchers) your work should be *legible* (to Future You, or other researchers) and *scalable* (it should work as well on 400,000 data points as on 40).

You will need help to do this. Therefore you will use Open Source solutions - these are analysis products which have a worldwide community of people using them, and the infrastructure which supports sharing advice and solutions. 

In practice, this means you are going to start by using R (you could use [Python](https://tomstafford.github.io/psy6422/appendices.html#python), but this module is based on R)

## Resources for current students

[Google Drive](https://drive.google.com/drive/folders/1tuaTS6RPYOXh-XByRffFS1FDzbvvFs_w) (UoS login required to access):

Includes slides and workbooks, as well as these specific documents

* [Timetable](https://docs.google.com/spreadsheets/d/1fyvjYhai6nIaOUymkUrlGIXL89cG76lI8bLXirPbaOw/edit?usp=drivesdk)
* [Useful information](https://docs.google.com/document/d/1kEDLaELoFyRBCsQLkZZP1PNbNaw2uUM6AAQhd42ExwQ/edit?usp=drivesdk)
* [Assessment Criteria](https://docs.google.com/spreadsheets/d/1DS91tnTtC8qPQHchAbzkOK57vvsSLIQc9FN3nPp9bQY/edit?usp=drivesdk)

And of course these pages (hosted on github, no login required)

You may particularly enjoy the [Reading list](extra-reading.html)

## Course Outline

In 2020 we are covering a compressed curriculum. The topics we cover are:

1. Module overview - ethics and aesthetics of visualisaion, the importance of reproducible workflows
2. Project organisation - fundamentals of data storage, syncronisation and sharing
3. R / Rstudio - introduction to the statistical computing language
4. Making graphs
5. Data Management
6. Data Management 2
7. Coding principles - fundamental principles of coding, writing good code, asking for help
8. Rmarkdown
9. Git and github
10. Publishing to pages - like this one!
11. Advanced topics

Stretch goals:

Unfortunately we won't have time this year for a number of advanced topics which I would like to cover. Hopefully next year:

* Jupyter notebooks
* The terminal / ssh
* Interactive visualisation with Shiny apps
* SQL

## Example Projects

The bulk of the assessment is to conduct and publish your own analysis project. Here is an example small project which gives an idea of what I mean

* SuperTues: [Published](https://tomstafford.github.io/supertues/), [repo](https://github.com/tomstafford/supertues)

Stretch goal is to build an interactive data visualisation using Shiny

* Here's one I built earlier [Power analyser](https://sheffield-university.shinyapps.io/decision_power/)



## More

* Russ Poldrack's [Advice for learning to code from scratch ](http://www.russpoldrack.org/2016/05/advice-for-learning-to-code-from-scratch.html)


